# Generated by Django 5.1.1 on 2024-09-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasteleria', '0002_productocategoria_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoCategoria',
        ),
    ]
